FROM mysql:8.0

# Definimos variables de entorno por defecto (se pueden cambiar al correr el contenedor)
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=db_sistema
ENV MYSQL_USER=user_sistema
ENV MYSQL_PASSWORD=userpassword

EXPOSE 3306