name: CI/CD Base de Datos

on:
  push:
    branches: [ "main" ]
    paths:
      - 'db-mysql/**' # Cambios en configuraciones de DB o scripts iniciales

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: bd-mysql
  CONTAINER_NAME: bd-mysql-container

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Autenticar en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Compilar y Subir Imagen a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        # Si usas el Dockerfile personalizado de MySQL
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./db-mysql
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Desplegar en EC2 Privada (Base de Datos)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_DATABASE_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true
          docker run -d -p 3306:3306 \
            -v mysql_data:/var/lib/mysql \
            -e MYSQL_ROOT_PASSWORD=rootpassword \
            -e MYSQL_DATABASE=db_sistema \
            -e MYSQL_USER=user_sistema \
            -e MYSQL_PASSWORD=userpassword \
            --name ${{ env.CONTAINER_NAME }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest